### ISSUE TITLE
Bad gateway for time range greater than 24H 

### ISSUE THREAD

**Issue by saibug** [darioef/loki-distributed-swarm#1]
Hi , 

Thank you for sharing this loki config . Is there any config / best practice for loading large data ? 
I'm facing this error `Bad Gateway ` when loading data from grafana UI . As community recommendation, I updated this section without success 

```
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-gateway:3100
  # added for perf 
  max_outstanding_per_tenant: 4096
  scheduler_worker_concurrency: 20

# added for perf 
query_scheduler:
  max_outstanding_requests_per_tenant: 4096
querier:
  query_ingesters_within: 2h

```

Also from ingester logs i'm seeing Out Of Memory !! 

```
loki-cluster_loki-ingester.1.zu9b0hfsa35a@server01   | level=error ts=2022-06-28T17:08:37.0482724Z caller=memcached.go:224 msg="failed to put to memcached" name=chunks err="server=10.0.44.36:11211: memcache: unexpected response line from \"set\": \"SERVER_ERROR Out of memory during read\\r\\n\""
loki-cluster_loki-ingester.1.zu9b0hfsa35a@server01    | level=error ts=2022-06-28T17:08:37.214132222Z caller=memcached.go:224 msg="failed to put to memcached" name=chunks err="server=10.0.44.36:11211: memcache: unexpected response line from \"set\": \"SERVER_ERROR Out of memory during read\\r\\n
```

Thank you for help in advance
